#!/bin/zsh

make

echo ---andExpr--- && ./compile src/test/scala/parsers/valid/expressions/andExpr.wacc && printf '' | ./refEmulate andExpr.s | sed -ne '/Emulation Output:/,$ p' > t1.txt && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/andExpr.wacc | sed -ne '/===========================================================/,$ p' > t2.txt && diff t1.txt t2.txt
echo ---andOverOrExpr--- && ./compile src/test/scala/parsers/valid/expressions/andOverOrExpr.wacc && printf '' | ./refEmulate andOverOrExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/andOverOrExpr.wacc
echo ---boolCalc--- && ./compile src/test/scala/parsers/valid/expressions/boolCalc.wacc && printf '' | ./refEmulate boolCalc.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/boolCalc.wacc
echo ---boolExpr1--- && ./compile src/test/scala/parsers/valid/expressions/boolExpr1.wacc && printf '' | ./refEmulate boolExpr1.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/boolExpr1.wacc
echo ---charComparisonExpr--- && ./compile src/test/scala/parsers/valid/expressions/charComparisonExpr.wacc && printf '' | ./refEmulate charComparisonExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/charComparisonExpr.wacc
echo ---divExpr--- && ./compile src/test/scala/parsers/valid/expressions/divExpr.wacc && printf '' | ./refEmulate divExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/divExpr.wacc
echo ---equalsExpr--- && ./compile src/test/scala/parsers/valid/expressions/equalsExpr.wacc && printf '' | ./refEmulate equalsExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/equalsExpr.wacc
echo ---equalsOverAnd--- && ./compile src/test/scala/parsers/valid/expressions/equalsOverAnd.wacc && printf '' | ./refEmulate equalsOverAnd.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/equalsOverAnd.wacc
echo ---equalsOverBool--- && ./compile src/test/scala/parsers/valid/expressions/equalsOverBool.wacc && printf '' | ./refEmulate equalsOverBool.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/equalsOverBool.wacc
echo ---equalsOverOr--- && ./compile src/test/scala/parsers/valid/expressions/equalsOverOr.wacc && printf '' | ./refEmulate equalsOverOr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/equalsOverOr.wacc
echo ---greaterEqExpr--- && ./compile src/test/scala/parsers/valid/expressions/greaterEqExpr.wacc && printf '' | ./refEmulate greaterEqExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/greaterEqExpr.wacc
echo ---greaterExpr--- && ./compile src/test/scala/parsers/valid/expressions/greaterExpr.wacc && printf '' | ./refEmulate greaterExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/greaterExpr.wacc
echo ---intCalc--- && ./compile src/test/scala/parsers/valid/expressions/intCalc.wacc && printf '' | ./refEmulate intCalc.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/intCalc.wacc
echo ---intExpr1--- && ./compile src/test/scala/parsers/valid/expressions/intExpr1.wacc && printf '' | ./refEmulate intExpr1.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/intExpr1.wacc
echo ---lessCharExpr--- && ./compile src/test/scala/parsers/valid/expressions/lessCharExpr.wacc && printf '' | ./refEmulate lessCharExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/lessCharExpr.wacc
echo ---lessEqExpr--- && ./compile src/test/scala/parsers/valid/expressions/lessEqExpr.wacc && printf '' | ./refEmulate lessEqExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/lessEqExpr.wacc
echo ---lessExpr--- && ./compile src/test/scala/parsers/valid/expressions/lessExpr.wacc && printf '' | ./refEmulate lessExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/lessExpr.wacc
echo ---longExpr--- && ./compile src/test/scala/parsers/valid/expressions/longExpr.wacc && printf '' | ./refEmulate longExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/longExpr.wacc
echo ---longExpr2--- && ./compile src/test/scala/parsers/valid/expressions/longExpr2.wacc && printf '' | ./refEmulate longExpr2.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/longExpr2.wacc
echo ---longExpr3--- && ./compile src/test/scala/parsers/valid/expressions/longExpr3.wacc && printf '' | ./refEmulate longExpr3.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/longExpr3.wacc
echo ---longSplitExpr--- && ./compile src/test/scala/parsers/valid/expressions/longSplitExpr.wacc && printf '' | ./refEmulate longSplitExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/longSplitExpr.wacc
echo ---longSplitExpr2--- && ./compile src/test/scala/parsers/valid/expressions/longSplitExpr2.wacc && printf '' | ./refEmulate longSplitExpr2.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/longSplitExpr2.wacc
echo ---minusExpr--- && ./compile src/test/scala/parsers/valid/expressions/minusExpr.wacc && printf '' | ./refEmulate minusExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/minusExpr.wacc
echo ---minusMinusExpr--- && ./compile src/test/scala/parsers/valid/expressions/minusMinusExpr.wacc && printf '' | ./refEmulate minusMinusExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/minusMinusExpr.wacc
echo ---minusNoWhitespaceExpr--- && ./compile src/test/scala/parsers/valid/expressions/minusNoWhitespaceExpr.wacc && printf '' | ./refEmulate minusNoWhitespaceExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/minusNoWhitespaceExpr.wacc
echo ---minusPlusExpr--- && ./compile src/test/scala/parsers/valid/expressions/minusPlusExpr.wacc && printf '' | ./refEmulate minusPlusExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/minusPlusExpr.wacc
echo ---modExpr--- && ./compile src/test/scala/parsers/valid/expressions/modExpr.wacc && printf '' | ./refEmulate modExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/modExpr.wacc
echo ---multExpr--- && ./compile src/test/scala/parsers/valid/expressions/multExpr.wacc && printf '' | ./refEmulate multExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/multExpr.wacc
echo ---multNoWhitespaceExpr--- && ./compile src/test/scala/parsers/valid/expressions/multNoWhitespaceExpr.wacc && printf '' | ./refEmulate multNoWhitespaceExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/multNoWhitespaceExpr.wacc
echo ---negBothDiv--- && ./compile src/test/scala/parsers/valid/expressions/negBothDiv.wacc && printf '' | ./refEmulate negBothDiv.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/negBothDiv.wacc
echo ---negBothMod--- && ./compile src/test/scala/parsers/valid/expressions/negBothMod.wacc && printf '' | ./refEmulate negBothMod.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/negBothMod.wacc
echo ---negDividendDiv--- && ./compile src/test/scala/parsers/valid/expressions/negDividendDiv.wacc && printf '' | ./refEmulate negDividendDiv.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/negDividendDiv.wacc
echo ---negDividendMod--- && ./compile src/test/scala/parsers/valid/expressions/negDividendMod.wacc && printf '' | ./refEmulate negDividendMod.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/negDividendMod.wacc
echo ---negDivisorDiv--- && ./compile src/test/scala/parsers/valid/expressions/negDivisorDiv.wacc && printf '' | ./refEmulate negDivisorDiv.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/negDivisorDiv.wacc
echo ---negDivisorMod--- && ./compile src/test/scala/parsers/valid/expressions/negDivisorMod.wacc && printf '' | ./refEmulate negDivisorMod.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/negDivisorMod.wacc
echo ---negExpr--- && ./compile src/test/scala/parsers/valid/expressions/negExpr.wacc && printf '' | ./refEmulate negExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/negExpr.wacc
echo ---notequalsExpr--- && ./compile src/test/scala/parsers/valid/expressions/notequalsExpr.wacc && printf '' | ./refEmulate notequalsExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/notequalsExpr.wacc
echo ---notExpr--- && ./compile src/test/scala/parsers/valid/expressions/notExpr.wacc && printf '' | ./refEmulate notExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/notExpr.wacc
echo ---ordAndchrExpr--- && ./compile src/test/scala/parsers/valid/expressions/ordAndchrExpr.wacc && printf '' | ./refEmulate ordAndchrExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/ordAndchrExpr.wacc
echo ---orExpr--- && ./compile src/test/scala/parsers/valid/expressions/orExpr.wacc && printf '' | ./refEmulate orExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/orExpr.wacc
echo ---plusExpr--- && ./compile src/test/scala/parsers/valid/expressions/plusExpr.wacc && printf '' | ./refEmulate plusExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/plusExpr.wacc
echo ---plusMinusExpr--- && ./compile src/test/scala/parsers/valid/expressions/plusMinusExpr.wacc && printf '' | ./refEmulate plusMinusExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/plusMinusExpr.wacc
echo ---plusNoWhitespaceExpr--- && ./compile src/test/scala/parsers/valid/expressions/plusNoWhitespaceExpr.wacc && printf '' | ./refEmulate plusNoWhitespaceExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/plusNoWhitespaceExpr.wacc
echo ---plusPlusExpr--- && ./compile src/test/scala/parsers/valid/expressions/plusPlusExpr.wacc && printf '' | ./refEmulate plusPlusExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/plusPlusExpr.wacc
echo ---sequentialCount--- && ./compile src/test/scala/parsers/valid/expressions/sequentialCount.wacc && printf '' | ./refEmulate sequentialCount.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/sequentialCount.wacc
echo ---stringEqualsExpr--- && ./compile src/test/scala/parsers/valid/expressions/stringEqualsExpr.wacc && printf '' | ./refEmulate stringEqualsExpr.s && printf '' | ./refCompile -x src/test/scala/parsers/valid/expressions/stringEqualsExpr.wacc